version: '3.4'

x-labels:
  &default-labels
  org.supernetworks.ci: ${CI:-false}
  org.supernetworks.version: ${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}

x-logging:
  &default-logging
  driver: journald

services:
  base:
    container_name: superbase
    image: ghcr.io/spr-networks/super_base:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: base
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_base:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_base:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    ports:
#      - "51280:51280/udp"
      - "127.0.0.1:5353:53"
      - "0.0.0.0:8000:80"
      - "127.0.0.1:4443:443"
    privileged: true
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/
      - ./state/base/:/state/base/
      - ./state/plugins/:/state/plugins/
      - ./plugins/:/plugins/
  superd:
    container_name: superd
    image: ghcr.io/spr-networks/super_superd:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: superd
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_superd:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_superd:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    privileged: true
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/base/:/configs/base/
      - ./:/super/
  dhcp:
    container_name: superdhcp
    image: ghcr.io/spr-networks/super_dhcp:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: dhcp
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_dhcp:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_dhcp:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    privileged: true
    depends_on:
      - "base"
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/:ro
      - ./configs/dhcp/:/configs/dhcp/
      - ./state/dhcp/:/state/dhcp/
      - ./state/plugins/mesh/:/state/plugins/mesh/:ro
      - /sys/fs/bpf:/sys/fs/bpf
  dhcp_client:
    container_name: superdhcp_client
    image: ghcr.io/spr-networks/super_dhcp_client:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: dhcp
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_dhcp_client:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_dhcp_client:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    privileged: true
    depends_on:
      - "base"
    logging: *default-logging
    entrypoint: /scripts/client.sh
    volumes:
      - ./configs/base/:/configs/base/:ro
      - ./state/dhcp-client/:/state/dhcp-client/
  dns:
    container_name: superdns
    image: ghcr.io/spr-networks/super_dns:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: dns
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_dns:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_dns:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    privileged: true
    logging: *default-logging
    depends_on:
      - "base"
    volumes:
      - ./configs/dns/:/configs/dns/
      - ./state/api/:/state/api/
      - ./state/dns/:/state/dns/
      - ./state/plugins/mesh/:/state/plugins/mesh/:ro
      - ./state/public/:/state/public/:ro
  wifid:
    container_name: superwifid
    image: ghcr.io/spr-networks/super_wifid:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: wifid
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_wifid:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_wifid:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    privileged: true
    logging: *default-logging
    depends_on:
      - "api"
      - "dhcp"
      - "multicast_udp_proxy"
    volumes:
      - ./configs/base/:/configs/base/:ro
      - ./configs/wifi/:/configs/wifi/
      - ./state/wifi/:/state/wifi/
  multicast_udp_proxy:
    container_name: super_multicast_udp_proxy
    image: ghcr.io/spr-networks/super_multicast_udp_proxy:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: multicast_udp_proxy
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_multicast_udp_proxy:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_multicast_udp_proxy:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    privileged: true
    depends_on:
      - "base"
      - "api"
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/:ro
      - ./state/public/:/state/public/:ro
      - ./state/plugins/mesh/:/state/plugins/mesh/:ro
  wireguard:
    container_name: superwireguard
    image: ghcr.io/spr-networks/super_wireguard:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: wireguard
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_wireguard:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_wireguard:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    privileged: true
    depends_on:
      - "base"
      - "dhcp"
      - "api"
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/:ro
      - ./configs/wireguard/:/configs/wireguard/
      - ./state/plugins/wireguard/:/state/plugins/wireguard/
      - ./state/plugins/mesh/:/state/plugins/mesh/:ro
      - ./state/dhcp/:/state/dhcp/
  frontend:
    container_name: superfrontend
    image: ghcr.io/spr-networks/super_frontend:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    entrypoint: ["cp", "-RT", "/app/build/", "/frontend/build"]
    build:
      context: frontend
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_frontend:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_frontend:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: none
    volumes:
      - ./frontend/:/frontend
  api:
    container_name: superapi
    image: ghcr.io/spr-networks/super_api:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: api
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_api:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_api:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    privileged: true
    restart: always
    depends_on:
      - "base"
      - "frontend"
      - "superd"
    logging: *default-logging
    volumes:
      - ./configs/auth/:/configs/auth/
      - ./configs/base/:/configs/base/
      - ./configs/devices/:/configs/devices/
      - ./configs/dns:/configs/dns/
      - ./configs/ppp:/configs/ppp/
      - ./configs/wifi/:/configs/wifi/
      - ./configs/wifi_uplink/:/configs/wifi_uplink/
      - ./configs/wireguard/:/configs/wireguard/
      - ./configs/scripts/:/configs/scripts/
      - ./configs/pfw/:/configs/pfw/
      - ./state/wifi/:/state/wifi/
      - ./state/dhcp/:/state/dhcp/
      - ./state/dns/:/state/dns/
      - ./state/api/:/state/api/
      - ./state/backups/:/state/backups/
      - ./state/base/:/state/base/
      - ./state/dhcp-client/:/state/dhcp-client/
      - ./state/plugins/:/state/plugins/
      - ./state/public/:/state/public/
      - ./frontend/build:/ui/
      - /var/log/journal:/var/log/journal:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  plugin-lookup:
    container_name: superplugin-lookup
    image: ghcr.io/spr-networks/super_plugin-lookup:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: plugin-lookup
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_plugin-lookup:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_plugin-lookup:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    logging: *default-logging
    depends_on:
      - "base"
      - "dns"
    volumes:
      - ./state/plugins/plugin-lookup/:/state/plugins/plugin-lookup/
  packet_logs:
    container_name: superpacket_logs
    image: ghcr.io/spr-networks/super_packet_logs:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: packet_logs
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_packet_logs:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_packet_logs:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    privileged: true
    restart: always
    logging: *default-logging
    volumes:
      - ./state/api/:/state/api/
      - ./state/plugins/packet_logs/:/state/plugins/packet_logs
      - ./configs/base/:/configs/base/:ro
      - /dev/log:/dev/log
  db:
    container_name: superdb
    image: ghcr.io/spr-networks/super_db:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: db
      labels: *default-labels
      x-bake:
        tags:
        - ghcr.io/spr-networks/super_db:latest${RELEASE_CHANNEL:-}
        - ghcr.io/spr-networks/super_db:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    network_mode: service:base
    depends_on:
      - "api"
    logging: *default-logging
    volumes:
      - ./configs/base/:/configs/base/:ro
      - ./configs/db/:/configs/db/
      - ./state/api/:/state/api/
      - ./state/plugins/db/:/state/plugins/db/
