#!/bin/bash
. configs/base/config.sh

cat << END
# Note, this is generated by gen_coredhcp_yaml.sh. Modify that to make changes
server4:
#  Listens on all interfaces when none are configured. Note that iptables should block dhcp from $WANIF
# 255.255.255.252 is a must for SPR tiny subnets
  plugins:
    - server_id: $LANIP
    - dns: $DNSIP
    - router: $LANIP
    - tiny_subnets
    - netmask: 255.255.255.252

END
