FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    qemu-system-aarch64 \
    qemu-utils \
    qemu-user-static \
    binfmt-support \
    e2fsprogs \
    cloud-guest-utils \
    zerofree \
    wget \
    xz-utils \
    curl \
    ca-certificates \
    gnupg \
    docker.io \
    zstd \
    && rm -rf /var/lib/apt/lists/*
