name: PI ISO Installer

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build_and_release:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Fetch tags
        run:  git fetch --tags
      - name: Get version from git
        run: echo "RELEASE_VERSION_TAG=$(git tag --contains $(git rev-parse HEAD) | grep -v clearfog)" >> $GITHUB_ENV
      - name: Authenticate to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Qemu emulation
        run: ./installer/qemu-setup-linux.sh

      # Build Ubuntu image
      - name: Download Ubuntu base image
        working-directory: ./installer/ubuntu
        run: ./pi-download-image.sh
      - name: Build Ubuntu install image
        working-directory: ./installer/ubuntu
        run: sudo ./pi-arm64-image-build.sh
      - name: Compress Ubuntu image
        run: sudo xz -T 0 -9 -z ./installer/ubuntu/data/spr.img
      - name: Attest Ubuntu ISO Provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "./installer/ubuntu/data/spr.img.xz"
          subject-name: "spr-ubuntu.img.xz"

      # Build Debian image
      - name: Build pi-builder image
        working-directory: ./installer/raspbian
        run: docker build -t spr-pi-builder -f Dockerfile.pi-builder .
      - name: Download Debian base image
        working-directory: ./installer/raspbian
        run: ./pi-download-image.sh
      - name: Build Debian install image
        working-directory: ./installer/raspbian
        run: sudo ./pi-arm64-image-build.sh
      - name: Compress Debian image
        run: sudo xz -T 0 -9 -z ./installer/raspbian/data/spr.img
      - name: Attest Debian ISO Provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "./installer/raspbian/data/spr.img.xz"
          subject-name: "spr-debian.img.xz"

      # Create release and upload
      - name: Create Release and Upload Images
        if: ${{ github.ref_name == 'main' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$RELEASE_VERSION_TAG" \
            --title "Release $RELEASE_VERSION_TAG" \
            ./installer/ubuntu/data/spr.img.xz#spr-ubuntu.img.xz \
            ./installer/raspbian/data/spr.img.xz#spr-debian.img.xz
